/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package u2_p2_pachecoochoa_ortegasoriano;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.Serializable;

/**
 *
 * @author luisa
 */
public class CampoTextHint extends javax.swing.JPanel implements Serializable{
    String hint = "|:CampoTextoHint:|";
    private Color gray = new Color(153,153,153);
    public enum tipoCampo {CADENA, NUMERICO};
    public tipoCampo tipo = tipoCampo.CADENA;
    /**
     * Creates new form CampoTextHint
     */
    
    public void setTipoCampo(tipoCampo tipo){
        this.tipo = tipo;
    }
    
    public void setHint(String text){
        hint = text;
        jTextField1.setText(hint);
    }
    
    public String getHint(){
        return hint;
    }
    
    public CampoTextHint() {
        initComponents();
        jTextField1.setText(hint);
        jTextField1.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent fe) {
                if(jTextField1.getText().startsWith(hint))jTextField1.setText("");
                jTextField1.setForeground(Color.BLACK);
            }

            @Override
            public void focusLost(FocusEvent fe) {
                if(jTextField1.getText().equals(""))jTextField1.setText(hint);
                jTextField1.setForeground(gray);
            }
        });
        
        jTextField1.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                if(tipo == tipoCampo.NUMERICO)if((e.getKeyChar() < 48 || e.getKeyChar() > 57) && e.getKeyChar() != '\b')
                        e.consume();
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
